src/Labs/BackBundle/Entity/Post.php
<?php

namespace Labs\BackBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Post
 *
 * @ORM\Table(name="post")
 * @ORM\Entity(repositoryClass="Labs\BackBundle\Repository\PostRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class Post
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     *
     * @Vich\UploadableField(mapping="blog_image", fileNameProperty="imageName")
     * @Assert\File(
     *     maxSize = "1M",
     *     mimeTypes = {"image/jpeg"},
     *     mimeTypesMessage = "le type de fichier ({{ type }}) est invalide"
     * )
     * @var File $imageFile
     */
    protected $imageFile;

    /**
     * @var string $imageName
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $imageName;

    /**
     * @var
     * @ORM\Column(name="docs_name", type="string", length=225)
     */
    protected $docsName;

    /**
     *
     * @Vich\UploadableField(mapping="blog_doc", fileNameProperty="documentName")
     * @Assert\File(
     *     maxSize="1M",
     *     mimeTypes={"application/pdf", "application/x-pdf"},
     *     mimeTypesMessage="Uplodez un fichier PDF valide"
     * )
     * @var File $documentFile
     */
    protected $documentFile;

    /**
     * @var string $documentName
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $documentName;



    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotNull(message="Veuiilez renseignez le titre")
     * @Assert\NotBlank(message="Ce champs ne peut être vide")
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(name="video_link", type="string", length=255, nullable=true)
     */
    protected $videoLink;


    /**
     * @var boolean
     *
     * @ORM\Column(name="status", type="boolean", length=255)
     */
    protected $status;


    /**
     * @var text
     *
     * @ORM\Column(name="content", type="text")
     */
    protected $content;


    /**
     * @var dateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    protected $created;


    /**
     * @Gedmo\Slug(fields={"title", "id"}, updatable=true, separator="_")
     * @ORM\Column(length=128, unique=true)
     */
    protected $slug;


    public function __construct()
    {
        $this->created = new \DateTime('now');
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param text $content
     *
     * @return Post
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return text
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return Post
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }


    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/posts';
    }

    public function getUploadDocDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/docs';
    }


    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadRootDocDir()
    {
        // On retourne le chemin relatif du docment pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDocDir();
    }


    /**
     * @return string
     */
    public function getAssertPath()
    {
        return $this->getUploadDir().'/'.$this->imageName;
    }

    /**
     * @return string
     */
    public function getAssertPathDoc()
    {
        return $this->getUploadDocDir().'/'.$this->documentName;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Post
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->created = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return Post
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set slug
     *
     * @param string $slug
     *
     * @return $this
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }


    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $doc
     *
     * @return Post
     */
    public function setDocumentFile(File $doc = null)
    {
        $this->documentFile = $doc;
        if ($doc) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->created = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @return File
     */
    public function getDocumentFile()
    {
        return $this->documentFile;
    }


    /**
     * Set documentName
     *
     * @param string $documentName
     *
     * @return Post
     */
    public function setDocumentName($documentName)
    {
        $this->documentName = $documentName;

        return $this;
    }

    /**
     * Get documentName
     *
     * @return string
     */
    public function getDocumentName()
    {
        return $this->documentName;
    }

    /**
     * Set videoLink
     *
     * @param string $videoLink
     *
     * @return Post
     */
    public function setVideoLink($videoLink)
    {
        $this->videoLink = $videoLink;

        return $this;
    }

    /**
     * Get videoLink
     *
     * @return string
     */
    public function getVideoLink()
    {
        return $this->videoLink;
    }

    /**
     * Set status
     *
     * @param boolean $status
     *
     * @return Post
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return boolean
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set docsName
     *
     * @param string $docsName
     *
     * @return Post
     */
    public function setDocsName($docsName)
    {
        $this->docsName = $docsName;

        return $this;
    }

    /**
     * Get docsName
     *
     * @return string
     */
    public function getDocsName()
    {
        return $this->docsName;
    }
}

src/Labs/BackBundle/Form/GalleryType.php
<?php

namespace Labs\BackBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GalleryType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class,array('label' => false, 'attr' => array('placeholder'=> 'Titre de L\'album', 'class' => 'form-control')))
            ->add('libelle', TextareaType::class,array('label' => false, 'attr' => array('placeholder'=> 'Resumé de l\'evenement', 'class' => 'form-control')))
            ->add('online',ChoiceType::class, array(
                'label' => false,
                'choices' => array(
                    'En Ligne' => true,
                    'Hors ligne' => false
                )
            ))
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Labs\BackBundle\Entity\Gallery'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'labs_adminbundle_gallery';
    }


}

src/Labs/BackBundle/Controller/GalleryController.php
<?php

namespace Labs\BackBundle\Controller;

use Labs\BackBundle\Entity\Gallery;
use Labs\BackBundle\Entity\Media;
use Labs\BackBundle\Form\GalleryType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;


/**
 * Class FormatController
 * @package Labs\BackBundle\Controller;
 * @Route("/gallery")
 */
class GalleryController extends Controller
{
    /**
     * @Route("/", name="dossier_index")
     * @Method({"GET"})
     */
    public function indexAction()
    {
        $dossiers = $this->getAllDossiers();
        return $this->render('LabsBackBundle:Gallery:index.html.twig',[
            'dossiers' => $dossiers
        ]);
    }

    /**
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @Route("/create", name="dossier_create")
     * @Method({"GET","POST"})
     */
    public function createAction()
    {
        $user = $this->getUser();
        $gallery = new Gallery();
        $draft = $this->get('draft_create')->DraftCreate($user, $gallery);
        return $this->redirectToRoute('dossier_draft', ['id' => $draft->getId(), 'user_id' => $user->getId()]);
    }


    /**
     * @param Request $request
     * @param Gallery $gallery
     * @return JsonResponse|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Symfony\Component\Security\Core\Exception\AccessDeniedException
     * @Route("/{id}/{user_id}/edit", name="dossier_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Gallery $gallery)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $datas = $em->getRepository('LabsBackBundle:Gallery')->getGallerysArticles($gallery, $user);
        if( null === $datas)
        {
            throw new AccessDeniedException("Vous n'êtes pas autorisé à modifier la galerie d'un utilisateur");
        }

        // Upload Medias
        if($request->isXmlHttpRequest()){
            $result = [];
            $media = $this->uploadMedia($request, $datas);
            if(null !== $media){
                $result = [
                    'results' => 'true',
                    'media'   => $media
                ];
                return new JsonResponse($result);
            }
            $result = ['results' => 'false'];
            return new JsonResponse($result);
        }

        $form = $this->createForm(GalleryType::class, $datas);
        $form->handleRequest($request);
        if($form->isValid() && $form->isSubmitted()){
            $datas->setDraft(1);
            $em->persist($datas);
            $em->flush();
            return $this->redirectToRoute('dossier_index');
        }
        return $this->render('LabsBackBundle:Gallery:edit_page.html.twig', [
            'form' => $form->createView(),
            'dossier' => $datas
        ]);

    }

    /**
     * @Route("/{id}/{user_id}/draft", name="dossier_draft")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @param Gallery $gallery
     * @return JsonResponse|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Symfony\Component\Form\Exception\UnexpectedTypeException
     * @throws \Symfony\Component\Form\Exception\LogicException
     * @throws \Symfony\Component\Form\Exception\AlreadySubmittedException
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \OutOfBoundsException
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    public function GalleryDraftAction(Request $request, Gallery $gallery)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $datas = $this->get('draft_create')->DraftCreate($user, $gallery);
        if( null === $datas)
        {
            throw new NotFoundHttpException('Dossier introuvable');
        }
        // Upload Medias
        if($request->isXmlHttpRequest()){
            $result = [];
            $media = $this->uploadMedia($request, $datas);
            if(null !== $media){
                $result = [
                    'results' => 'true',
                    'media'   => $media
                ];
                return new JsonResponse($result);
            }
            $result = ['results' => 'false'];
            return new JsonResponse($result);
        }

        $form = $this->createForm(GalleryType::class, $datas);
        $form->add('draft', SubmitType::class, array(
            'label' => 'Enregistrer comme brouillon',
            'attr'  => array('class' => 'btn btn-danger')
        ));

        $form->handleRequest($request);
        if($form->isValid() && $form->isSubmitted()){

            if ($form->get('draft')->isClicked()){
                $datas->setDraft(-1);
                $datas->setOnline(0);
            } else {
                $datas->setDraft(1);
            }

            $em->persist($datas);
            $em->flush();
            return $this->redirectToRoute('dossier_index');
        }
        return $this->render('LabsBackBundle:Gallery:draft_page.html.twig', [
            'form' => $form->createView(),
            'dossier' => $datas
        ]);
    }

    /**
     * @param Gallery $gallery
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/{id}/delete", name="dossier_delete")
     * @Method({"GET","DELETE"})
     */
    public function deleteAction(Gallery $gallery)
    {
        $em = $this->getDoctrine()->getManager();
        $formats = $em->getRepository('LabsBackBundle:Gallery')->find($gallery);
        if( null === $formats)
            throw new NotFoundHttpException('element '.$formats.' n\'existe pas');
        else
            $em->remove($formats);
        $em->flush();
        return $this->redirectToRoute('dossier_index');
    }

    /**
     * @return array
     */
    private function getAllDossiers()
    {
      $em = $this->getDoctrine()->getManager();
      $entity = $em->getRepository('LabsBackBundle:Gallery')->getAll();
      if(null === $entity){
          throw new NotFoundHttpException('Entity introuvable');
      }
      return $entity;
    }


    /**
     * @param Request $request
     * @param Gallery $gallery
     * @return bool
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    private function uploadMedia(Request $request, Gallery $gallery)
    {
        $em = $this->getDoctrine()->getManager();
        $media = new Media();
        $dossier = $em->getRepository('LabsBackBundle:Gallery')->getGallerys($gallery);
        /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
        $file = $request->files->get('file');
        $fileName = $dossier->getSlug().'_'.md5(uniqid()).'.'.$file->guessExtension();
        $file->move(
            $this->getParameter('gallery_directory'),
            $fileName
        );
        $media->setUrl($fileName);
        $media->setGallery($dossier);
        $em->persist($media);
        $em->flush($media);
        return $media->getId();
    }


}

src/Labs/BackBundle/Resources/views/Gallery/edit_page.html.twig
{% extends 'LabsBackBundle::admin.html.twig' %}
{% block title %}{{ 'Gestion des Galeries | La financesengage.com ' }}{% endblock %}
{% block stylesheets %}
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{ asset('adminLayout/assets/global/plugins/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('adminLayout/assets/global/plugins/dropzone/basic.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
{% endblock %}
{% block body %}
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <h1 class="page-title"> {{'Gestion des Galeries'}}
            <small>{{ '| Edition de galerie photos' }}</small>
        </h1>
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="{{ path('admin_homepage') }}">{{ 'Dashboard'|capitalize }}</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="{{ path('dossier_index') }}">{{ 'Photos'|capitalize }}</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span>{{ 'Brouillons'|capitalize }}</span>
                </li>
            </ul>
        </div>
        <!-- BEGIN PAGE LIST-->
        <div class="row">
            <div class="col-md-12">
                {% if app.session.flashBag.has('success') %}
                    <div class="alert alert-success" role="alert">
                        {% for msg in app.session.flashBag.get('success') %}
                            <strong> Succès </strong>{{ msg }}.
                        {% endfor %}
                    </div>
                {% endif %}
                {% if app.session.flashBag.has('error') %}
                    <div class="alert alert-danger" role="alert">
                        {% for msg in app.session.flashBag.get('error') %}
                            <strong> Erreur d'ajout </strong>{{ msg }}.
                        {% endfor %}
                    </div>
                {% endif %}
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <i class="icon-settings font-dark"></i>
                            <span class="caption-subject bold uppercase"> {{ 'Edition Galerie' }}</span>
                        </div>
                        <div class="actions">
                            <a href="{{ path('dossier_index') }}" class="btn sbold uppercase btn-outline yellow-gold"><i class="fa fa-plus"></i> {{ 'afficher la liste'|upper }} </a>
                        </div>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
                <!-- BEGIN SAMPLE FORM PORTLET-->
                <div class="portlet box yellow-gold">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-draft"></i> {{'Brouillons Album'|capitalize}} | <small class="text-bold">Brouillon Edition de l'album - {% if dossier.name|length > 0 %}{{ dossier.name }}{% endif %}</small>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        {{ form_start(form, { 'action': path('dossier_edit', {'id' : dossier.id , 'user_id': app.user.id}), attr : { 'class':'form-horizontal', 'novalidate': 'novalidate'}}) }}
                        {{ form_errors(form) }}
                        <div class="form-body">
                            <div class="form-group">
                                <label class="col-md-3 control-label">{{ 'Status de l\'album' }}</label>
                                <div class="col-md-9">
                                    {{ form_row(form.online) }}
                                    {{ form_errors(form.online) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">{{ 'Titre de l\'album' }}</label>
                                <div class="col-md-9">
                                    {{ form_row(form.name) }}
                                    {{ form_errors(form.name) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">{{ 'Resumé de l\'évenement' }}</label>
                                <div class="col-md-9">
                                    {{ form_row(form.libelle) }}
                                    {{ form_errors(form.libelle) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div action="{{ path('dossier_draft', {'id' : dossier.id, 'user_id': app.user.id }) }}" class="dropzone dropzone-file-area" id="my-dropzone" data-name="Gallery" style="width: 700px; margin-top: 10px;">
                                    <h3 class="sbold">Faites glisser des fichiers ici <span> ou Sélectionnez des fichiers sur l'ordinateur en cliquant ici</span></h3>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                        <div class="col-md-12">
                            <div class="portlet light portlet-fit ">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class=" icon-layers font-green"></i>
                                        <span class="caption-subject font-green bold uppercase">Liste des photos</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="mt-element-card mt-element-overlay">
                                        <div class="row">
                                        {% for media in dossier.medias %}
                                            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                                                <div class="mt-card-item">
                                                    <div class="mt-card-avatar mt-overlay-1">
                                                        <img src="{{ asset(media.assertPath|imagine_filter('my_thumb_off_back')) }}" />
                                                        <div class="mt-overlay">
                                                            <ul class="mt-info">
                                                                <li>
                                                                    <a class="btn default btn-outline" href="javascript:;">
                                                                        <i class="icon-magnifier"></i>
                                                                    </a>
                                                                </li>
                                                                <li>
                                                                    <a class="btn default btn-outline" href="javascript:;">
                                                                        <i class="icon-link"></i>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                        <div class="form-actions">
                            <div class="row col-md-offset-3">
                                <div class="col-md-4">
                                     <div class="text-right">
                                        <a href="{{ path('dossier_index') }}" class="btn green">{{ 'Retour a la liste' }} <i class="icon-database-add position-right"></i></a>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                     <div class="text-right">
                                        <button type="submit" class="btn yellow-gold">Enregistrer & Continuer <i class="icon-database-add position-right"></i></button>
                                    </div>
                                </div>
                            </div>
                        {{ form_end(form) }}
                    </div>
                </div>
                <!-- END SAMPLE FORM PORTLET-->
            </div>
        </div>
        <!-- END PAGE LIST-->
    </div>
    <!-- END PAGE HEADER-->
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('adminLayout/assets/global/plugins/dropzone/dropzone.min.js') }}"></script>
{% endblock %}
{% block extra %}
    {{ parent() }}
        <script type="text/javascript" src="{{ asset('adminLayout/assets/pages/scripts/form-dropzone.js') }}"></script>
{% endblock %}